// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transflo.Data;

#nullable disable

namespace Transflo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transflo.Models.TblDriver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "d.emilang8187@aol.edu",
                            FirstName = "DaquanCarpenter",
                            LastName = "EmiLang",
                            PhoneNumber = "1-385-662-6735"
                        },
                        new
                        {
                            Id = 2,
                            Email = "m_signemeyers@yahoo.couk",
                            FirstName = "MichaelBattle",
                            LastName = "SigneMeyers",
                            PhoneNumber = "1-291-196-0252"
                        },
                        new
                        {
                            Id = 3,
                            Email = "l-jadenkirkland4541@protonmail.edu",
                            FirstName = "JadenKirkland",
                            LastName = "LillithBurt",
                            PhoneNumber = "1-106-494-2935"
                        },
                        new
                        {
                            Id = 4,
                            Email = "oliviakennedyhavivacarr5881@yahoo.com",
                            FirstName = "OliviaKennedy",
                            LastName = "HavivaCarr",
                            PhoneNumber = "1-955-465-1148"
                        },
                        new
                        {
                            Id = 5,
                            Email = "silashampton-emeraldcastillo3347@outlook.com",
                            FirstName = "SilasHampton",
                            LastName = "EmeraldCastillo",
                            PhoneNumber = "1-768-533-1262"
                        },
                        new
                        {
                            Id = 6,
                            Email = "e-bakerhensley@google.couk",
                            FirstName = "BakerHensley",
                            LastName = "EvelynHewitt",
                            PhoneNumber = "1-661-244-2344"
                        },
                        new
                        {
                            Id = 7,
                            Email = "molliestewartaaronmueller@hotmail.org",
                            FirstName = "AaronMueller",
                            LastName = "MollieStewart",
                            PhoneNumber = "1-340-657-6271"
                        },
                        new
                        {
                            Id = 8,
                            Email = "c-fatimaanderson@icloud.com",
                            FirstName = "FatimaAnderson",
                            LastName = "CameronMejia",
                            PhoneNumber = "1-412-570-4345"
                        },
                        new
                        {
                            Id = 9,
                            Email = "lbreeatkins2793@yahoo.com",
                            FirstName = "LuneaRollins",
                            LastName = "BreeAtkins",
                            PhoneNumber = "1-789-773-5167"
                        },
                        new
                        {
                            Id = 10,
                            Email = "b-indiafinch9502@protonmail.couk",
                            FirstName = "BertHorton",
                            LastName = "IndiaFinch",
                            PhoneNumber = "1-244-431-4333"
                        },
                        new
                        {
                            Id = 11,
                            Email = "n-maririchmond9959@google.ca",
                            FirstName = "NehruRobles",
                            LastName = "MariRichmond",
                            PhoneNumber = "(317) 248-7118"
                        },
                        new
                        {
                            Id = 12,
                            Email = "s_inezstein@icloud.org",
                            FirstName = "ShannonPayne",
                            LastName = "InezStein",
                            PhoneNumber = "1-855-264-2510"
                        },
                        new
                        {
                            Id = 13,
                            Email = "k_kessieknapp1410@outlook.edu",
                            FirstName = "KeeganRoberson",
                            LastName = "KessieKnapp",
                            PhoneNumber = "(896) 552-8732"
                        },
                        new
                        {
                            Id = 14,
                            Email = "sgracespears@google.org",
                            FirstName = "SukiShelton",
                            LastName = "GraceSpears",
                            PhoneNumber = "(372) 621-5439"
                        },
                        new
                        {
                            Id = 15,
                            Email = "larissabarnett-vladimirhawkins@google.couk",
                            FirstName = "VladimirHawkins",
                            LastName = "LarissaBarnett",
                            PhoneNumber = "1-957-331-3663"
                        },
                        new
                        {
                            Id = 16,
                            Email = "a.kelsiepetersen@aol.com",
                            FirstName = "AileeMckay",
                            LastName = "KelsiePetersen",
                            PhoneNumber = "1-477-118-0177"
                        },
                        new
                        {
                            Id = 17,
                            Email = "derekgibson.jeanettesosa6229@aol.com",
                            FirstName = "DerekGibson",
                            LastName = "JeanetteSosa",
                            PhoneNumber = "1-311-513-6023"
                        },
                        new
                        {
                            Id = 18,
                            Email = "smaxinesmall4906@aol.couk",
                            FirstName = "SageGomez",
                            LastName = "MaxineSmall",
                            PhoneNumber = "(546) 620-0682"
                        },
                        new
                        {
                            Id = 19,
                            Email = "penelopeburns.kaiavila8611@hotmail.net",
                            FirstName = "KaiAvila",
                            LastName = "PenelopeBurns",
                            PhoneNumber = "1-927-363-8715"
                        },
                        new
                        {
                            Id = 20,
                            Email = "pearlbyrd_sydneepetersen214@aol.couk",
                            FirstName = "SydneePetersen",
                            LastName = "PearlByrd",
                            PhoneNumber = "1-423-275-5341"
                        },
                        new
                        {
                            Id = 21,
                            Email = "rinanguyen.jilliancline@outlook.ca",
                            FirstName = "RinaNguyen",
                            LastName = "JillianCline",
                            PhoneNumber = "(382) 101-7627"
                        },
                        new
                        {
                            Id = 22,
                            Email = "i.mercedesconner@outlook.org",
                            FirstName = "MercedesConner",
                            LastName = "IrisCruz",
                            PhoneNumber = "(216) 773-8211"
                        },
                        new
                        {
                            Id = 23,
                            Email = "keelydavidsonhakeemchapman@aol.ca",
                            FirstName = "HakeemChapman",
                            LastName = "KeelyDavidson",
                            PhoneNumber = "(424) 597-5604"
                        },
                        new
                        {
                            Id = 24,
                            Email = "kchavabishop6766@protonmail.couk",
                            FirstName = "KeikoVillarreal",
                            LastName = "ChavaBishop",
                            PhoneNumber = "(386) 353-9018"
                        },
                        new
                        {
                            Id = 25,
                            Email = "w.maceysawyer2335@hotmail.net",
                            FirstName = "MaceySawyer",
                            LastName = "WhitneyMullins",
                            PhoneNumber = "(484) 746-7982"
                        },
                        new
                        {
                            Id = 26,
                            Email = "laceywilkinson.quinlanjoseph5642@aol.net",
                            FirstName = "QuinlanJoseph",
                            LastName = "LaceyWilkinson",
                            PhoneNumber = "(564) 992-4461"
                        },
                        new
                        {
                            Id = 27,
                            Email = "elianaodonnell_lukelynn@hotmail.ca",
                            FirstName = "LukeLynn",
                            LastName = "ElianaOdonnell",
                            PhoneNumber = "1-335-563-5450"
                        },
                        new
                        {
                            Id = 28,
                            Email = "t.linusmcfadden@hotmail.edu",
                            FirstName = "LinusMcfadden",
                            LastName = "TeeganGarrett",
                            PhoneNumber = "(101) 766-0358"
                        },
                        new
                        {
                            Id = 29,
                            Email = "a.lesterholder@google.net",
                            FirstName = "LesterHolder",
                            LastName = "AspenGoodwin",
                            PhoneNumber = "(884) 816-3536"
                        },
                        new
                        {
                            Id = 30,
                            Email = "n.roannaconley@google.net",
                            FirstName = "NissimMalone",
                            LastName = "RoannaConley",
                            PhoneNumber = "1-208-403-1931"
                        },
                        new
                        {
                            Id = 31,
                            Email = "jaquelynhouse_illanabarron9995@google.org",
                            FirstName = "IllanaBarron",
                            LastName = "JaquelynHouse",
                            PhoneNumber = "1-475-723-4516"
                        },
                        new
                        {
                            Id = 32,
                            Email = "alexaatkinson-kylanwest4601@google.org",
                            FirstName = "KylanWest",
                            LastName = "AlexaAtkinson",
                            PhoneNumber = "(345) 388-2751"
                        },
                        new
                        {
                            Id = 33,
                            Email = "gwendolynmarks-bevisvazquez1093@protonmail.com",
                            FirstName = "BevisVazquez",
                            LastName = "GwendolynMarks",
                            PhoneNumber = "1-590-439-7588"
                        },
                        new
                        {
                            Id = 34,
                            Email = "georgiaguzman-justinpeck@icloud.couk",
                            FirstName = "JustinPeck",
                            LastName = "GeorgiaGuzman",
                            PhoneNumber = "(771) 364-8503"
                        },
                        new
                        {
                            Id = 35,
                            Email = "vmiriamperry@icloud.net",
                            FirstName = "MiriamPerry",
                            LastName = "VirginiaArmstrong",
                            PhoneNumber = "1-784-170-4050"
                        },
                        new
                        {
                            Id = 36,
                            Email = "r.adeleneal@icloud.com",
                            FirstName = "RyderSears",
                            LastName = "AdeleNeal",
                            PhoneNumber = "1-474-456-1915"
                        },
                        new
                        {
                            Id = 37,
                            Email = "heatherrobinson-mageeelliott@google.edu",
                            FirstName = "MageeElliott",
                            LastName = "HeatherRobinson",
                            PhoneNumber = "1-679-602-4215"
                        },
                        new
                        {
                            Id = 38,
                            Email = "j.hannaingram458@icloud.org",
                            FirstName = "HannaIngram",
                            LastName = "JessicaLeon",
                            PhoneNumber = "(441) 538-6524"
                        },
                        new
                        {
                            Id = 39,
                            Email = "khumcgee8799@google.ca",
                            FirstName = "HuMcgee",
                            LastName = "KarinaStephens",
                            PhoneNumber = "(815) 287-4631"
                        },
                        new
                        {
                            Id = 40,
                            Email = "j_quynnbean@icloud.edu",
                            FirstName = "JamesonCarey",
                            LastName = "QuynnBean",
                            PhoneNumber = "(359) 559-8501"
                        },
                        new
                        {
                            Id = 41,
                            Email = "dbrynnesoto@yahoo.couk",
                            FirstName = "DahliaSosa",
                            LastName = "BrynneSoto",
                            PhoneNumber = "1-712-588-5516"
                        },
                        new
                        {
                            Id = 42,
                            Email = "orenromero-orlagillespie@protonmail.org",
                            FirstName = "OrenRomero",
                            LastName = "OrlaGillespie",
                            PhoneNumber = "(276) 687-2822"
                        },
                        new
                        {
                            Id = 43,
                            Email = "arsenionguyen-mayaguerra@protonmail.ca",
                            FirstName = "ArsenioNguyen",
                            LastName = "MayaGuerra",
                            PhoneNumber = "(327) 854-2601"
                        },
                        new
                        {
                            Id = 44,
                            Email = "medgedean_tallulahcardenas1854@outlook.org",
                            FirstName = "TallulahCardenas",
                            LastName = "MedgeDean",
                            PhoneNumber = "(267) 252-1466"
                        },
                        new
                        {
                            Id = 45,
                            Email = "bradleygreer.yuributler4506@icloud.edu",
                            FirstName = "BradleyGreer",
                            LastName = "YuriButler",
                            PhoneNumber = "(877) 555-2367"
                        },
                        new
                        {
                            Id = 46,
                            Email = "n_odetteallen@icloud.ca",
                            FirstName = "NicholeEngland",
                            LastName = "OdetteAllen",
                            PhoneNumber = "1-575-818-6726"
                        },
                        new
                        {
                            Id = 47,
                            Email = "d_heatherduffy2681@outlook.net",
                            FirstName = "HeatherDuffy",
                            LastName = "DesireeBerg",
                            PhoneNumber = "1-412-500-8115"
                        },
                        new
                        {
                            Id = 48,
                            Email = "judithstuart_shanaschmidt@hotmail.com",
                            FirstName = "ShanaSchmidt",
                            LastName = "JudithStuart",
                            PhoneNumber = "1-312-534-6742"
                        },
                        new
                        {
                            Id = 49,
                            Email = "signelawson_kenyonmorrow5250@yahoo.com",
                            FirstName = "KenyonMorrow",
                            LastName = "SigneLawson",
                            PhoneNumber = "(378) 486-0126"
                        },
                        new
                        {
                            Id = 50,
                            Email = "e-ursahayden@yahoo.net",
                            FirstName = "ElianaLevy",
                            LastName = "UrsaHayden",
                            PhoneNumber = "(561) 576-7311"
                        },
                        new
                        {
                            Id = 51,
                            Email = "z_jolenefarmer@hotmail.edu",
                            FirstName = "ZephaniaPeters",
                            LastName = "JoleneFarmer",
                            PhoneNumber = "(743) 457-0562"
                        },
                        new
                        {
                            Id = 52,
                            Email = "nellemcintyre-courtneybradford@hotmail.edu",
                            FirstName = "CourtneyBradford",
                            LastName = "NelleMcintyre",
                            PhoneNumber = "1-718-531-1560"
                        },
                        new
                        {
                            Id = 53,
                            Email = "sopolinebradley.kaioconnor8798@yahoo.org",
                            FirstName = "Kaiconnor",
                            LastName = "SopolineBradley",
                            PhoneNumber = "(310) 668-7703"
                        },
                        new
                        {
                            Id = 54,
                            Email = "n.dexterbaird4112@yahoo.edu",
                            FirstName = "DexterBaird",
                            LastName = "NatalieStout",
                            PhoneNumber = "(693) 222-4362"
                        },
                        new
                        {
                            Id = 55,
                            Email = "beverlycannonrandallmartinez@outlook.net",
                            FirstName = "RandallMartinez",
                            LastName = "BeverlyCannon",
                            PhoneNumber = "1-847-644-3606"
                        },
                        new
                        {
                            Id = 56,
                            Email = "akirestinrichard1812@google.com",
                            FirstName = "KirestinRichard",
                            LastName = "AlisaDickerson",
                            PhoneNumber = "1-486-506-6749"
                        },
                        new
                        {
                            Id = 57,
                            Email = "h-nevadaknapp@icloud.org",
                            FirstName = "HopRivers",
                            LastName = "NevadaKnapp",
                            PhoneNumber = "1-367-757-8767"
                        },
                        new
                        {
                            Id = 58,
                            Email = "madonnaflorestylerday1957@aol.ca",
                            FirstName = "TylerDay",
                            LastName = "MadonnaFlores",
                            PhoneNumber = "(687) 467-6296"
                        },
                        new
                        {
                            Id = 59,
                            Email = "i_ainsleyolsen9030@aol.couk",
                            FirstName = "Indira",
                            LastName = "AinsleyOlsen",
                            PhoneNumber = "(617) 670-8520"
                        },
                        new
                        {
                            Id = 60,
                            Email = "h_erinbullock792@hotmail.couk",
                            FirstName = "ErinBullock",
                            LastName = "HaleyTravis",
                            PhoneNumber = "1-374-119-7643"
                        },
                        new
                        {
                            Id = 61,
                            Email = "abasiagutierrez5823@outlook.couk",
                            FirstName = "BasiaGutierrez",
                            LastName = "AprilBoyd",
                            PhoneNumber = "1-262-474-9411"
                        },
                        new
                        {
                            Id = 62,
                            Email = "ahardingbarlow4576@icloud.com",
                            FirstName = "HardingBarlow",
                            LastName = "AnnGonzales",
                            PhoneNumber = "1-375-877-4494"
                        },
                        new
                        {
                            Id = 63,
                            Email = "ufaithmorrow@aol.com",
                            FirstName = "UptonBarrett",
                            LastName = "FaithMorrow",
                            PhoneNumber = "1-354-827-8548"
                        },
                        new
                        {
                            Id = 64,
                            Email = "colettekeith.sylvestercrawford6797@outlook.edu",
                            FirstName = "SylvesterCrawford",
                            LastName = "ColetteKeith",
                            PhoneNumber = "1-771-288-6916"
                        },
                        new
                        {
                            Id = 65,
                            Email = "serenalangleycalistashaw@hotmail.net",
                            FirstName = "CalistaShaw",
                            LastName = "SerenaLangley",
                            PhoneNumber = "1-435-421-7578"
                        },
                        new
                        {
                            Id = 66,
                            Email = "sarahmeadows_gillianvincent@aol.edu",
                            FirstName = "SarahMeadows",
                            LastName = "GillianVincent",
                            PhoneNumber = "1-365-876-3854"
                        },
                        new
                        {
                            Id = 67,
                            Email = "m.rhodabrennan@icloud.net",
                            FirstName = "MayBowen",
                            LastName = "RhodaBrennan",
                            PhoneNumber = "1-422-751-8916"
                        },
                        new
                        {
                            Id = 68,
                            Email = "l_lilliancarlson7672@hotmail.org",
                            FirstName = "LilahBooker",
                            LastName = "LillianCarlson",
                            PhoneNumber = "1-831-936-2515"
                        },
                        new
                        {
                            Id = 69,
                            Email = "i-kimmoran@yahoo.ca",
                            FirstName = "IgnaciaCooper",
                            LastName = "Kim",
                            PhoneNumber = "1-580-713-7085"
                        },
                        new
                        {
                            Id = 70,
                            Email = "s.brittanytyler@protonmail.edu",
                            FirstName = "Simon",
                            LastName = "Brittany",
                            PhoneNumber = "(315) 850-4861"
                        },
                        new
                        {
                            Id = 71,
                            Email = "k-darrylball7785@protonmail.couk",
                            FirstName = "Kylan",
                            LastName = "Darryl",
                            PhoneNumber = "1-315-791-5630"
                        },
                        new
                        {
                            Id = 72,
                            Email = "k.sachaschneider@protonmail.ca",
                            FirstName = "Sacha",
                            LastName = "Kylee",
                            PhoneNumber = "(289) 655-5743"
                        },
                        new
                        {
                            Id = 73,
                            Email = "ddanielbyers@aol.org",
                            FirstName = "Daniel",
                            LastName = "Dora",
                            PhoneNumber = "(787) 210-4312"
                        },
                        new
                        {
                            Id = 74,
                            Email = "m.kerryparks@aol.net",
                            FirstName = "Margaret",
                            LastName = "Kerry",
                            PhoneNumber = "(865) 555-7723"
                        },
                        new
                        {
                            Id = 75,
                            Email = "kirstenmccoyraeoneil@aol.ca",
                            FirstName = "Rae",
                            LastName = "Kirsten",
                            PhoneNumber = "1-424-763-8233"
                        },
                        new
                        {
                            Id = 76,
                            Email = "n.blakealvarez2060@yahoo.com",
                            FirstName = "Blake",
                            LastName = "Neve",
                            PhoneNumber = "1-547-559-4581"
                        },
                        new
                        {
                            Id = 77,
                            Email = "s.biancarocha851@yahoo.org",
                            FirstName = "Simone",
                            LastName = "Bianca",
                            PhoneNumber = "1-931-645-7474"
                        },
                        new
                        {
                            Id = 78,
                            Email = "fkimpetersen6582@outlook.edu",
                            FirstName = "Fallon",
                            LastName = "Kim",
                            PhoneNumber = "(402) 769-8920"
                        },
                        new
                        {
                            Id = 79,
                            Email = "winifredbrennan-risamcfadden@icloud.com",
                            FirstName = "Risa",
                            LastName = "Winifred",
                            PhoneNumber = "(303) 578-8781"
                        },
                        new
                        {
                            Id = 80,
                            Email = "j.ivorymontgomery@aol.net",
                            FirstName = "Jaden",
                            LastName = "Ivory",
                            PhoneNumber = "1-615-435-6512"
                        },
                        new
                        {
                            Id = 81,
                            Email = "harriettyson-fultoncarrillo@google.com",
                            FirstName = "Fulton",
                            LastName = "Harriet",
                            PhoneNumber = "1-577-403-4430"
                        },
                        new
                        {
                            Id = 82,
                            Email = "lisandrasanchez.germanesanchez@outlook.com",
                            FirstName = "Lisandra",
                            LastName = "Germane",
                            PhoneNumber = "(448) 558-8797"
                        },
                        new
                        {
                            Id = 83,
                            Email = "guywebster-deniseburns@google.com",
                            FirstName = "Guy",
                            LastName = "Denise",
                            PhoneNumber = "(548) 250-1527"
                        },
                        new
                        {
                            Id = 84,
                            Email = "ezoerocha@outlook.com",
                            FirstName = "Eaton",
                            LastName = "Zoe",
                            PhoneNumber = "(304) 855-6088"
                        },
                        new
                        {
                            Id = 85,
                            Email = "utawalton.destinyhaynes@icloud.com",
                            FirstName = "Uta",
                            LastName = "Destiny",
                            PhoneNumber = "(183) 386-5388"
                        },
                        new
                        {
                            Id = 86,
                            Email = "tmadonnagraham5497@yahoo.edu",
                            FirstName = "Thomas",
                            LastName = "Madonna",
                            PhoneNumber = "1-918-878-4536"
                        },
                        new
                        {
                            Id = 87,
                            Email = "warrencruz.teegansosa@aol.edu",
                            FirstName = "Warren",
                            LastName = "Teegan",
                            PhoneNumber = "(768) 403-7136"
                        },
                        new
                        {
                            Id = 88,
                            Email = "msandrasolomon9088@google.net",
                            FirstName = "Maxwell",
                            LastName = "Sandra",
                            PhoneNumber = "1-619-660-6168"
                        },
                        new
                        {
                            Id = 89,
                            Email = "noelallen_meganmatthews@hotmail.com",
                            FirstName = "Megan",
                            LastName = "Noel",
                            PhoneNumber = "(765) 341-6786"
                        },
                        new
                        {
                            Id = 90,
                            Email = "tanneoliver7309@aol.com",
                            FirstName = "Tara",
                            LastName = "Anne",
                            PhoneNumber = "(516) 552-7857"
                        },
                        new
                        {
                            Id = 91,
                            Email = "r_deaconkline@protonmail.com",
                            FirstName = "Deacon",
                            LastName = "Rana",
                            PhoneNumber = "1-397-464-7587"
                        },
                        new
                        {
                            Id = 92,
                            Email = "kelliepark-viviandouglas@aol.couk",
                            FirstName = "Vivian",
                            LastName = "Kellie",
                            PhoneNumber = "(386) 348-2252"
                        },
                        new
                        {
                            Id = 93,
                            Email = "o-dairosales5824@icloud.couk",
                            FirstName = "Orli",
                            LastName = "Dai",
                            PhoneNumber = "1-711-512-6036"
                        },
                        new
                        {
                            Id = 94,
                            Email = "nelletalley_gavinjones@outlook.edu",
                            FirstName = "Gavin",
                            LastName = "Nelle",
                            PhoneNumber = "1-254-484-2138"
                        },
                        new
                        {
                            Id = 95,
                            Email = "zephreaton-rileyhensley1459@aol.com",
                            FirstName = "Zephr",
                            LastName = "Riley",
                            PhoneNumber = "1-163-596-4606"
                        },
                        new
                        {
                            Id = 96,
                            Email = "n_xylakey9554@google.org",
                            FirstName = "Nolan",
                            LastName = "Xyla",
                            PhoneNumber = "(880) 381-8869"
                        },
                        new
                        {
                            Id = 97,
                            Email = "melyssamosleynoelleadams4313@outlook.couk",
                            FirstName = "Melyssa",
                            LastName = "Noelle",
                            PhoneNumber = "1-613-821-6621"
                        },
                        new
                        {
                            Id = 98,
                            Email = "pvedahull@aol.edu",
                            FirstName = "Phelan",
                            LastName = "Veda",
                            PhoneNumber = "(563) 872-0273"
                        },
                        new
                        {
                            Id = 99,
                            Email = "mdaracombs9158@protonmail.edu",
                            FirstName = "Madaline",
                            LastName = "Dara",
                            PhoneNumber = "(458) 590-3565"
                        },
                        new
                        {
                            Id = 100,
                            Email = "l_lenoreatkinson@protonmail.net",
                            FirstName = "Lani",
                            LastName = "Lenore",
                            PhoneNumber = "1-623-338-7621"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
